// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSammour.Infrastructure.data;

#nullable disable

namespace SmartSammour.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816163355_InitialPostgreSql")]
    partial class InitialPostgreSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartSammour.Core.Entities.AddOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExtraPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("AddOns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExtraPrice = 200m,
                            Name = "Chatting",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 2,
                            ExtraPrice = 200m,
                            Name = "Chatting",
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 3,
                            ExtraPrice = 200m,
                            Name = "Chatting",
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 4,
                            ExtraPrice = 200m,
                            Name = "Chatting",
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 5,
                            ExtraPrice = 200m,
                            Name = "Chatting",
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 6,
                            ExtraPrice = 150m,
                            Name = "Search Engine Optimization",
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 7,
                            ExtraPrice = 150m,
                            Name = "Search Engine Optimization",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 8,
                            ExtraPrice = 150m,
                            Name = "Search Engine Optimization",
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 9,
                            ExtraPrice = 150m,
                            Name = "Search Engine Optimization",
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 10,
                            ExtraPrice = 500m,
                            Name = "Recommendations Engine",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 11,
                            ExtraPrice = 500m,
                            Name = "Recommendations Engine",
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 12,
                            ExtraPrice = 500m,
                            Name = "Recommendations Engine",
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 13,
                            ExtraPrice = 500m,
                            Name = "Recommendations Engine",
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 14,
                            ExtraPrice = 500m,
                            Name = "Recommendations Engine",
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 15,
                            ExtraPrice = 200m,
                            Name = "Push Notifications",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 16,
                            ExtraPrice = 200m,
                            Name = "Push Notifications",
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 17,
                            ExtraPrice = 200m,
                            Name = "Push Notifications",
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 18,
                            ExtraPrice = 400m,
                            Name = "Push Notifications",
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 19,
                            ExtraPrice = 500m,
                            Name = "Push Notifications",
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 20,
                            ExtraPrice = 1000m,
                            Name = "In-app purchases",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 21,
                            ExtraPrice = 1000m,
                            Name = "In-app purchases",
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 22,
                            ExtraPrice = 1000m,
                            Name = "In-app purchases",
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 23,
                            ExtraPrice = 1000m,
                            Name = "In-app purchases",
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 24,
                            ExtraPrice = 1000m,
                            Name = "In-app purchases",
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 25,
                            ExtraPrice = 300m,
                            Name = "Admin dashboard",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 26,
                            ExtraPrice = 300m,
                            Name = "Admin dashboard",
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 27,
                            ExtraPrice = 300m,
                            Name = "Admin dashboard",
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 28,
                            ExtraPrice = 300m,
                            Name = "Admin dashboard",
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 29,
                            ExtraPrice = 200m,
                            Name = "CMS Content Management",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 30,
                            ExtraPrice = 200m,
                            Name = "CMS Content Management",
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 31,
                            ExtraPrice = 200m,
                            Name = "CMS Content Management",
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 32,
                            ExtraPrice = 700m,
                            Name = "AI Integration",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 33,
                            ExtraPrice = 700m,
                            Name = "AI Integration",
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 34,
                            ExtraPrice = 700m,
                            Name = "AI Integration",
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 35,
                            ExtraPrice = 700m,
                            Name = "AI Integration",
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 36,
                            ExtraPrice = 700m,
                            Name = "AI Integration",
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 37,
                            ExtraPrice = 200m,
                            Name = "Calculation",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 38,
                            ExtraPrice = 200m,
                            Name = "Calculation",
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 39,
                            ExtraPrice = 200m,
                            Name = "Calculation",
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 40,
                            ExtraPrice = 200m,
                            Name = "Calculation",
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 41,
                            ExtraPrice = 200m,
                            Name = "Calculation",
                            ServiceId = 6
                        });
                });

            modelBuilder.Entity("SmartSammour.Core.Entities.Inquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("SmartSammour.Core.Entities.InquiryAddOn", b =>
                {
                    b.Property<int>("InquiryId")
                        .HasColumnType("integer");

                    b.Property<int>("AddOnId")
                        .HasColumnType("integer");

                    b.HasKey("InquiryId", "AddOnId");

                    b.HasIndex("AddOnId");

                    b.ToTable("InquiryAddOn");
                });

            modelBuilder.Entity("SmartSammour.Core.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ExtraFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IncludeDomainAnalysis")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeDomainRegistration")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeHosting")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("StartFrom")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The most competitive pricing in Jordan for a professionally built product. You get clean, working software — done right, without the extras. Ideal if you know exactly what you need and want it delivered efficiently.",
                            ExtraFee = 0m,
                            IncludeDomainAnalysis = false,
                            IncludeDomainRegistration = false,
                            IncludeHosting = false,
                            IsActive = true,
                            Name = "Basic",
                            StartFrom = 50m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Domain requirement added to your requirement , built to a higher standard — plus domain setup, more thorough testing, and closer attention to detail throughout. The right choice if this product represents your business to real customers and needs to hold up under real use.",
                            ExtraFee = 200m,
                            IncludeDomainAnalysis = true,
                            IncludeDomainRegistration = true,
                            IncludeHosting = true,
                            IsActive = true,
                            Name = "Professional",
                            StartFrom = 400m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Everything in Professional, but as one complete system — a backend API, a website, and a mobile app, all built together and designed to work as a single product. Best for businesses that want to launch across web and mobile from day one, without stitching together separate builds later.",
                            ExtraFee = 500m,
                            IncludeDomainAnalysis = true,
                            IncludeDomainRegistration = true,
                            IncludeHosting = true,
                            IsActive = true,
                            Name = "Inclusive",
                            StartFrom = 2500m
                        });
                });

            modelBuilder.Entity("SmartSammour.Core.Entities.PlanService", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("PlanId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("PlanServices");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            PlanId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            PlanId = 1,
                            ServiceId = 3
                        },
                        new
                        {
                            PlanId = 1,
                            ServiceId = 4
                        },
                        new
                        {
                            PlanId = 1,
                            ServiceId = 5
                        },
                        new
                        {
                            PlanId = 2,
                            ServiceId = 1
                        },
                        new
                        {
                            PlanId = 2,
                            ServiceId = 2
                        },
                        new
                        {
                            PlanId = 2,
                            ServiceId = 3
                        },
                        new
                        {
                            PlanId = 2,
                            ServiceId = 4
                        },
                        new
                        {
                            PlanId = 2,
                            ServiceId = 5
                        },
                        new
                        {
                            PlanId = 2,
                            ServiceId = 6
                        },
                        new
                        {
                            PlanId = 3,
                            ServiceId = 6
                        });
                });

            modelBuilder.Entity("SmartSammour.Core.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 50m,
                            Description = "Custom website, built to spec",
                            Name = "Website"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 1000m,
                            Description = "interactive web application",
                            Name = "E-commerce Web Application"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 1000m,
                            Description = "interactive web application",
                            Name = "Social Media Web Application"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 1000m,
                            Description = "interactive web application",
                            Name = "Booking system Web Application"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 1200m,
                            Description = "Cross-platform mobile app (iOS + Android)",
                            Name = "Mobile App"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 2500m,
                            Description = "Integrated website, mobile application, and backend/API solution",
                            Name = "Full Software Solution"
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 0m,
                            Description = "We are listing to your needs, this type have no predefined price, we will contact you for more details",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("SmartSammour.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmartSammour.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmartSammour.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSammour.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmartSammour.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSammour.Core.Entities.AddOn", b =>
                {
                    b.HasOne("SmartSammour.Core.Entities.Service", "Service")
                        .WithMany("AddOns")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SmartSammour.Core.Entities.Inquiry", b =>
                {
                    b.HasOne("SmartSammour.Core.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSammour.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SmartSammour.Core.Entities.InquiryAddOn", b =>
                {
                    b.HasOne("SmartSammour.Core.Entities.AddOn", "AddOn")
                        .WithMany()
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartSammour.Core.Entities.Inquiry", "Inquiry")
                        .WithMany("SelectedAddOns")
                        .HasForeignKey("InquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");

                    b.Navigation("Inquiry");
                });

            modelBuilder.Entity("SmartSammour.Core.Entities.PlanService", b =>
                {
                    b.HasOne("SmartSammour.Core.Entities.Plan", "Plan")
                        .WithMany("PlanServices")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSammour.Core.Entities.Service", "Service")
                        .WithMany("PlanServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SmartSammour.Core.Entities.Inquiry", b =>
                {
                    b.Navigation("SelectedAddOns");
                });

            modelBuilder.Entity("SmartSammour.Core.Entities.Plan", b =>
                {
                    b.Navigation("PlanServices");
                });

            modelBuilder.Entity("SmartSammour.Core.Entities.Service", b =>
                {
                    b.Navigation("AddOns");

                    b.Navigation("PlanServices");
                });
#pragma warning restore 612, 618
        }
    }
}
